import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div>
      <h1>This is Heading</h1>
      <p>I am Piyush Garg and I am going to start my youtube journey with react series. In this series, we are going to learn and understand react. Also after the completion of this series, you would be able to design and code complex react UI's and be ready for production-grade use of react.js.
        In this video, we are going to understand the folder structure and the boilerplate code that is being generated by the create-react-app template.
      </p>
      <h2>Footer exe</h2>
    </div>

  );
}

export default App;
